version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    env_file:
      - .env.docker
    ports:
      - 3000:3000

    extra_hosts:
      - "pg_host:192.168.0.26"
      - "mysql_host:192.168.0.26"
      - "redis_host:192.168.0.26"
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
# Declare the volumes that our application uses.
#volumes:
#  db_data: