require('jquery')
require('jszip')
require('./pdfmake/build/pdfmake.js')
require('./pdfmake/build/vfs_fonts')
require("datatables.net")
require("datatables.net-bs4")
require("datatables.net-bs4/css/dataTables.bootstrap4.min.css")
require("datatables.net-responsive")
require("datatables.net-responsive-bs4")
require("datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css")
require("datatables.net-buttons")
require("datatables.net-buttons-bs4")
require("datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css")
require("datatables.net-buttons/js/buttons.colVis.js")
require("datatables.net-buttons/js/buttons.html5.js")
require("datatables.net-buttons/js/buttons.colVis.js")


