# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
#
# If you want to be able to access a string config[:site_title], for example:
#
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#
# 'name' is the name that appears in the edit form
#
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
#
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
#
# Some Examples:
#
app_name:
  name: Application Name
  default: "<b>Risk</b>Monitor"
  type: string
short_app_name:
  name: Short Application Name
  default: "<b>R</b>Mtr"
  type: string
site_title:
  name: Site Title
  default: "Risk Monitor - Emoney plc"
  type: string

site_description:
  name: Description for Google
  default: Risk Monitor System
  type: text

default_product_base_risk:
  name: Default risk factor for product if base_risk for product is null
  default: 1.01
  type: float

default_bankwire_in_base_risk:
  name: Default risk factor for bankwire
  default: 1.01
  type: float

time_lapse_factor:
  name: Default factor for time lapse
  default: 0.98
  type: float

min_base_risk:
  name: Default minimum base risk
  default: 4.0
  type: float

max_base_risk:
  name: Default maximum base risk
  default: 20.0
  type: float

threshold_factor_for_sanction_list:
  name: Default thresold factor for minimum rank into search result
  default: 0.3
  type: float


amount_eq:
  name: "Calculated Recursion Eq"
  default: "((x / 1000) ** 3) * 1.5"
  type: string
recursion_eq:
  name: "Calculated Recursion Eq"
  default: "x ** 4"
  type: string
country_eq:
  name: "Calculated Recursion Eq"
  default: "5((x - 1)**2)"
  type: string
product_eq:
  name: "Calculated Product Eq"
  default: "(x / 1 * 100) - 100"
  type: string
attention_eq:
  name: "Attenfion Factor Eq"
  default: "((product_factor_calculated * recursion_factor_calculated * amount_factor_calculated * countries_factor_calculated) + 100) / 100"
  type: string
