# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
#
# If you want to be able to access a string config[:site_title], for example:
#
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#
# 'name' is the name that appears in the edit form
#
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
#
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
#
# Some Examples:
#
app_name:
  name: Application Name
  default: "<b>Risk</b>Monitor"
  type: string
short_app_name:
  name: Short Application Name
  default: "<b>R</b>Mtr"
  type: string
site_title:
  name: Site Title
  default: "Risk Monitor - Emoney plc"
  type: string

site_description:
  name: Description for Google
  default: Risk Monitor System
  type: text

default_product_base_risk:
  name: Default risk factor for product if base_risk for product is null
  default: 1.01
  type: float

default_bankwire_in_base_risk:
  name: Default risk factor for bankwire
  default: 1.01
  type: float

time_lapse_factor:
  name: Default factor for time lapse
  default: 0.98
  type: float

min_base_risk:
  name: Default minimum base risk
  default: 4.0
  type: float

max_base_risk:
  name: Default maximum base risk
  default: 20.0
  type: float

factor_for_amount:
  name: Default factor for amount ((((((product_base_risk.percentage_of(1)) - 100) * nr_of_recursive_operations) * (factor_for_amount * amount/divisor_amount_for_factor)) + 100) / 100)
  default: 1.5
  type: float

divisor_amount_for_factor:
  name: Default divisor per amount for factor
  default: 1000
  type: integer

threshold_factor_for_sanction_list:
  name: Default thresold factor for minimum rank into search result
  default: 0.3
  type: float
