default_pg: &default_pg
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>
  migrations_paths: db/core_pg_migrate
  host: <%= ENV.fetch("PGSQL_HOST") %>
  username: <%= ENV.fetch("PGSQL_USER") %>
  password: <%= ENV.fetch("PGSQL_PASSWORD") %>
  schema_search_path: "public"

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 50
  reconnect: true
  wait_timeout: 900
  timeout: 10000
  host: <%= ENV.fetch("MYSQL_HOST") %>
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>

development:
  risk:
    <<: *default
    database: risk_production
    migrations_paths: db/risk_migrate
  core:
    <<: *default
    database: dbconti_prod
  core_pg:
    <<: *default_pg
    database: data_analysis_production

test:
  risk:
    <<: *default
    database: risk_test
  core:
    <<: *default
    database: dbconti_prod
  core_pg:
    <<: *default_pg
    database: data_analysis_test

production:
  risk:
    <<: *default
    migrations_paths: db/risk_migrate
    database: risk_production
  core:
    <<: *default
    database: dbconti_prod
  core_pg:
    <<: *default_pg
    database: data_analysis_production
