---
:concurrency: 40
:queues:
  - massive
  - critical
  - default
  - mailers
  - serial

:limits:
  massive: 25
  default: 10
  mailers: 3
  critical: 1
  serial: 1

:process_limits:
  massive: 25
  critical: 14
  serial: 1

:schedule:
#  trigger_worker:
#    every: '1m'
#    class: TriggerWorker
#  trigger_customer_worker:
#    every: '2m'
#    class: TriggerCustomerWorker
