---
:concurrency: 40
:queues:
  - massive
  - critical
  - default
  - mailers
  - serial

:limits:
  massive: 5
  default: 10
  mailers: 3
  critical: 35
  serial: 1

:process_limits:
  massive: 5
  critical: 35
  serial: 1

##### SET FOR INIT
#:schedule:
#  trigger_worker:
#    every: '1m'
#    class: TriggerWorker
#  trigger_customer_worker:
#    every: '5m'
#    class: TriggerCustomerWorker
#  daily_worker:
#    cron: '00 01 * * *'
#    class: DailyWorker