---
:concurrency: 50
:queues:
  - massive
  - critical
  - default
  - mailers
  - serial

:limits:
  massive: 1
  default: 1
  mailers: 1
  critical: 1
  serial: 1

:process_limits:
  massive: 1
  critical: 1
  serial: 1

:schedule:
  trigger_worker:
    every: '1m'
    class: TriggerWorker
