---
:concurrency: 100
:queues:
  - massive
  - critical
  - default
  - mailers
  - serial

:limits:
  massive: 50
  default: 15
  mailers: 5
  critical: 1
  serial: 1

:process_limits:
  massive: 50
  critical: 1
  serial: 1

:schedule:
  trigger_worker:
    every: '1m'
    class: TriggerWorker
