---
:concurrency: 50
:queues:
  - massive
  - critical
  - default
  - mailers
  - serial

:limits:
  massive: 25
  default: 10
  mailers: 5
  critical: 1
  serial: 1

:process_limits:
  massive: 25
  critical: 1
  serial: 1

:schedule:
  enqueuer_worker:
    cron: '0 * * * *'
    class: EnqueuerWorker
