---
:concurrency: 40
:queues:
  - massive
  - critical
  - default
  - mailers
  - serial

:limits:
  massive: 25
  default: 10
  mailers: 3
  critical: 14
  serial: 10

:process_limits:
  massive: 25
  critical: 14
  serial: 10

:schedule:
  trigger_worker:
    every: '1m'
    class: TriggerWorker
  trigger_customer_worker:
    every: '5m'
    class: TriggerCustomerWorker
  daily_worker:
    cron: '00 01 * * *'
    class: DailyWorker