---
:concurrency: 50
:queues:
  - massive
  - critical
  - default
  - mailers
  - serial

:limits:
  massive: 25
  default: 15
  mailers: 5
  critical: 1
  serial: 10

:process_limits:
  massive: 25
  critical: 1
  serial: 10

:schedule:
  enqueuer_worker:
    every: '1m'
    class: EnqueuerWorker
